name: Deploy Tiddlywiki To Github Pages

on:
  push:
    branches:
      - master
  schedule:
    - cron: '0 * * * *'

jobs:
  deploy:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v2-beta
        with:
          node-version: '16'

      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: |
            **/node_modules
          key: ${{ runner.os }}-${{ hashFiles('**/package.json') }}

      - name: Install Dependency
        run: npm install

      - name: Build Library
        run: npm run buildonline && npm run buildlibrary

      - name: Make offline cache
        run: npx workbox injectManifest workbox-config.js

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          
      - name: Mirror the Github organization repos to Gitee.
        uses: Yikun/hub-mirror-action@master
        with:
          # 必选，需要同步的Github用户（源）
          src: github/tiddly-gittly
          # 必选，需要同步到的Gitee的用户（目的）
          dst: gitee/tiddly-gittly
          # 必选，Gitee公钥对应的私钥，https://gitee.com/profile/sshkeys
          dst_key: ${{ secrets.GITEE_PRIVATE_KEY }}
          # 必选，Gitee对应的用于创建仓库的token，https://gitee.com/profile/personal_access_tokens
          dst_token:  ${{ secrets.GITEE_TOKEN }}
          account_type: org
          white_list: 'TiddlyWiki-CPL'
          static_list: 'TiddlyWiki-CPL'
          force_update: true
